name: Deploy changes

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          curl ${{ secrets.VERCEL_DEPLOY_URL }}

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          curl ${{ secrets.VERCEL_DEPLOY_URL_DEV }}
