name: Deploy changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy changes
        run: curl ${{ secrets.VERCEL_DEPLOY_URL }}
